-- Baseline schema. Flyway owns every change from here on; do not edit this file
-- after it has run anywhere. Add a new versioned migration instead.
CREATE TABLE movies (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL CHECK (length(trim(title)) > 0),
    release_year INTEGER CHECK (release_year BETWEEN 1888 AND 2100),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
